<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Complete Request
 *
 * Generated from protobuf message <code>spooled.v1.CompleteRequest</code>
 */
class CompleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     */
    protected $job_id = '';
    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     */
    protected $worker_id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct result = 3;</code>
     */
    protected $result = null;
    /**
     * Lease fencing token from the dequeued Job. When set, the completion
     * succeeds only if it matches the job's current lease.
     *
     * Generated from protobuf field <code>string lease_id = 4;</code>
     */
    protected $lease_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $job_id
     *     @type string $worker_id
     *     @type \Google\Protobuf\Struct $result
     *     @type string $lease_id
     *           Lease fencing token from the dequeued Job. When set, the completion
     *           succeeds only if it matches the job's current lease.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->job_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     * @return string
     */
    public function getWorkerId()
    {
        return $this->worker_id;
    }

    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->worker_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct result = 3;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct result = 3;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Lease fencing token from the dequeued Job. When set, the completion
     * succeeds only if it matches the job's current lease.
     *
     * Generated from protobuf field <code>string lease_id = 4;</code>
     * @return string
     */
    public function getLeaseId()
    {
        return $this->lease_id;
    }

    /**
     * Lease fencing token from the dequeued Job. When set, the completion
     * succeeds only if it matches the job's current lease.
     *
     * Generated from protobuf field <code>string lease_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLeaseId($var)
    {
        GPBUtil::checkString($var, True);
        $this->lease_id = $var;

        return $this;
    }

}

