<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Dequeue Response
 *
 * Generated from protobuf message <code>spooled.v1.DequeueResponse</code>
 */
class DequeueResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .spooled.v1.Job jobs = 1;</code>
     */
    private $jobs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spooled\V1\Job[] $jobs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .spooled.v1.Job jobs = 1;</code>
     * @return RepeatedField<\Spooled\V1\Job>
     */
    public function getJobs()
    {
        return $this->jobs;
    }

    /**
     * Generated from protobuf field <code>repeated .spooled.v1.Job jobs = 1;</code>
     * @param \Spooled\V1\Job[] $var
     * @return $this
     */
    public function setJobs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Spooled\V1\Job::class);
        $this->jobs = $arr;

        return $this;
    }

}
