<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Enqueue Response
 *
 * Generated from protobuf message <code>spooled.v1.EnqueueResponse</code>
 */
class EnqueueResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     */
    protected $job_id = '';
    /**
     * false if idempotent (existing job)
     *
     * Generated from protobuf field <code>bool created = 2;</code>
     */
    protected $created = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $job_id
     *     @type bool $created
     *           false if idempotent (existing job)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->job_id = $var;

        return $this;
    }

    /**
     * false if idempotent (existing job)
     *
     * Generated from protobuf field <code>bool created = 2;</code>
     * @return bool
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * false if idempotent (existing job)
     *
     * Generated from protobuf field <code>bool created = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkBool($var);
        $this->created = $var;

        return $this;
    }

}

