<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Enqueue Request
 *
 * Generated from protobuf message <code>spooled.v1.EnqueueRequest</code>
 */
class EnqueueRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     */
    protected $queue_name = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 2;</code>
     */
    protected $payload = null;
    /**
     * Generated from protobuf field <code>int32 priority = 3;</code>
     */
    protected $priority = 0;
    /**
     * Generated from protobuf field <code>int32 max_retries = 4;</code>
     */
    protected $max_retries = 0;
    /**
     * Generated from protobuf field <code>int32 timeout_seconds = 5;</code>
     */
    protected $timeout_seconds = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_at = 6;</code>
     */
    protected $scheduled_at = null;
    /**
     * Generated from protobuf field <code>string idempotency_key = 7;</code>
     */
    protected $idempotency_key = '';
    /**
     * Generated from protobuf field <code>map<string, string> tags = 8;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $queue_name
     *     @type \Google\Protobuf\Struct $payload
     *     @type int $priority
     *     @type int $max_retries
     *     @type int $timeout_seconds
     *     @type \Google\Protobuf\Timestamp $scheduled_at
     *     @type string $idempotency_key
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @return string
     */
    public function getQueueName()
    {
        return $this->queue_name;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQueueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 2;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getPayload()
    {
        return $this->payload;
    }

    public function hasPayload()
    {
        return isset($this->payload);
    }

    public function clearPayload()
    {
        unset($this->payload);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 2;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 priority = 3;</code>
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Generated from protobuf field <code>int32 priority = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkInt32($var);
        $this->priority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_retries = 4;</code>
     * @return int
     */
    public function getMaxRetries()
    {
        return $this->max_retries;
    }

    /**
     * Generated from protobuf field <code>int32 max_retries = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRetries($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_retries = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 timeout_seconds = 5;</code>
     * @return int
     */
    public function getTimeoutSeconds()
    {
        return $this->timeout_seconds;
    }

    /**
     * Generated from protobuf field <code>int32 timeout_seconds = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeoutSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeout_seconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_at = 6;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getScheduledAt()
    {
        return $this->scheduled_at;
    }

    public function hasScheduledAt()
    {
        return isset($this->scheduled_at);
    }

    public function clearScheduledAt()
    {
        unset($this->scheduled_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_at = 6;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setScheduledAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->scheduled_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 7;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->idempotency_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

