<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Fail Request
 *
 * Generated from protobuf message <code>spooled.v1.FailRequest</code>
 */
class FailRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     */
    protected $job_id = '';
    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     */
    protected $worker_id = '';
    /**
     * Generated from protobuf field <code>string error = 3;</code>
     */
    protected $error = '';
    /**
     * Whether to retry or move to DLQ
     *
     * Generated from protobuf field <code>bool retry = 4;</code>
     */
    protected $retry = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $job_id
     *     @type string $worker_id
     *     @type string $error
     *     @type bool $retry
     *           Whether to retry or move to DLQ
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->job_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     * @return string
     */
    public function getWorkerId()
    {
        return $this->worker_id;
    }

    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->worker_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error = 3;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

    /**
     * Whether to retry or move to DLQ
     *
     * Generated from protobuf field <code>bool retry = 4;</code>
     * @return bool
     */
    public function getRetry()
    {
        return $this->retry;
    }

    /**
     * Whether to retry or move to DLQ
     *
     * Generated from protobuf field <code>bool retry = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRetry($var)
    {
        GPBUtil::checkBool($var);
        $this->retry = $var;

        return $this;
    }

}
