<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Fail Response
 *
 * Generated from protobuf message <code>spooled.v1.FailResponse</code>
 */
class FailResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>bool will_retry = 2;</code>
     */
    protected $will_retry = false;
    /**
     * Generated from protobuf field <code>int32 next_retry_delay_secs = 3;</code>
     */
    protected $next_retry_delay_secs = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type bool $will_retry
     *     @type int $next_retry_delay_secs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool will_retry = 2;</code>
     * @return bool
     */
    public function getWillRetry()
    {
        return $this->will_retry;
    }

    /**
     * Generated from protobuf field <code>bool will_retry = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setWillRetry($var)
    {
        GPBUtil::checkBool($var);
        $this->will_retry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 next_retry_delay_secs = 3;</code>
     * @return int
     */
    public function getNextRetryDelaySecs()
    {
        return $this->next_retry_delay_secs;
    }

    /**
     * Generated from protobuf field <code>int32 next_retry_delay_secs = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNextRetryDelaySecs($var)
    {
        GPBUtil::checkInt32($var);
        $this->next_retry_delay_secs = $var;

        return $this;
    }

}
