<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Get Job Response
 *
 * Generated from protobuf message <code>spooled.v1.GetJobResponse</code>
 */
class GetJobResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.spooled.v1.Job job = 1;</code>
     */
    protected $job = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spooled\V1\Job $job
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.Job job = 1;</code>
     * @return \Spooled\V1\Job|null
     */
    public function getJob()
    {
        return $this->job;
    }

    public function hasJob()
    {
        return isset($this->job);
    }

    public function clearJob()
    {
        unset($this->job);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.Job job = 1;</code>
     * @param \Spooled\V1\Job $var
     * @return $this
     */
    public function setJob($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\Job::class);
        $this->job = $var;

        return $this;
    }

}

