<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Get Queue Stats Request
 *
 * Generated from protobuf message <code>spooled.v1.GetQueueStatsRequest</code>
 */
class GetQueueStatsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     */
    protected $queue_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $queue_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @return string
     */
    public function getQueueName()
    {
        return $this->queue_name;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQueueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue_name = $var;

        return $this;
    }

}
