<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Get Queue Stats Response
 *
 * Generated from protobuf message <code>spooled.v1.GetQueueStatsResponse</code>
 */
class GetQueueStatsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     */
    protected $queue_name = '';
    /**
     * Generated from protobuf field <code>int64 pending = 2;</code>
     */
    protected $pending = 0;
    /**
     * Generated from protobuf field <code>int64 scheduled = 3;</code>
     */
    protected $scheduled = 0;
    /**
     * Generated from protobuf field <code>int64 processing = 4;</code>
     */
    protected $processing = 0;
    /**
     * Generated from protobuf field <code>int64 completed = 5;</code>
     */
    protected $completed = 0;
    /**
     * Generated from protobuf field <code>int64 failed = 6;</code>
     */
    protected $failed = 0;
    /**
     * Generated from protobuf field <code>int64 deadletter = 7;</code>
     */
    protected $deadletter = 0;
    /**
     * Generated from protobuf field <code>int64 total = 8;</code>
     */
    protected $total = 0;
    /**
     * Age of oldest pending job
     *
     * Generated from protobuf field <code>int64 max_age_ms = 9;</code>
     */
    protected $max_age_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $queue_name
     *     @type int|string $pending
     *     @type int|string $scheduled
     *     @type int|string $processing
     *     @type int|string $completed
     *     @type int|string $failed
     *     @type int|string $deadletter
     *     @type int|string $total
     *     @type int|string $max_age_ms
     *           Age of oldest pending job
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @return string
     */
    public function getQueueName()
    {
        return $this->queue_name;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQueueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 pending = 2;</code>
     * @return int|string
     */
    public function getPending()
    {
        return $this->pending;
    }

    /**
     * Generated from protobuf field <code>int64 pending = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPending($var)
    {
        GPBUtil::checkInt64($var);
        $this->pending = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 scheduled = 3;</code>
     * @return int|string
     */
    public function getScheduled()
    {
        return $this->scheduled;
    }

    /**
     * Generated from protobuf field <code>int64 scheduled = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScheduled($var)
    {
        GPBUtil::checkInt64($var);
        $this->scheduled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 processing = 4;</code>
     * @return int|string
     */
    public function getProcessing()
    {
        return $this->processing;
    }

    /**
     * Generated from protobuf field <code>int64 processing = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcessing($var)
    {
        GPBUtil::checkInt64($var);
        $this->processing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 completed = 5;</code>
     * @return int|string
     */
    public function getCompleted()
    {
        return $this->completed;
    }

    /**
     * Generated from protobuf field <code>int64 completed = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->completed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 failed = 6;</code>
     * @return int|string
     */
    public function getFailed()
    {
        return $this->failed;
    }

    /**
     * Generated from protobuf field <code>int64 failed = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFailed($var)
    {
        GPBUtil::checkInt64($var);
        $this->failed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 deadletter = 7;</code>
     * @return int|string
     */
    public function getDeadletter()
    {
        return $this->deadletter;
    }

    /**
     * Generated from protobuf field <code>int64 deadletter = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeadletter($var)
    {
        GPBUtil::checkInt64($var);
        $this->deadletter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total = 8;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Age of oldest pending job
     *
     * Generated from protobuf field <code>int64 max_age_ms = 9;</code>
     * @return int|string
     */
    public function getMaxAgeMs()
    {
        return $this->max_age_ms;
    }

    /**
     * Age of oldest pending job
     *
     * Generated from protobuf field <code>int64 max_age_ms = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxAgeMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_age_ms = $var;

        return $this;
    }

}
