<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Heartbeat Response
 *
 * Generated from protobuf message <code>spooled.v1.HeartbeatResponse</code>
 */
class HeartbeatResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool acknowledged = 1;</code>
     */
    protected $acknowledged = false;
    /**
     * Signal to worker to stop accepting new jobs
     *
     * Generated from protobuf field <code>bool should_drain = 2;</code>
     */
    protected $should_drain = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $acknowledged
     *     @type bool $should_drain
     *           Signal to worker to stop accepting new jobs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool acknowledged = 1;</code>
     * @return bool
     */
    public function getAcknowledged()
    {
        return $this->acknowledged;
    }

    /**
     * Generated from protobuf field <code>bool acknowledged = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcknowledged($var)
    {
        GPBUtil::checkBool($var);
        $this->acknowledged = $var;

        return $this;
    }

    /**
     * Signal to worker to stop accepting new jobs
     *
     * Generated from protobuf field <code>bool should_drain = 2;</code>
     * @return bool
     */
    public function getShouldDrain()
    {
        return $this->should_drain;
    }

    /**
     * Signal to worker to stop accepting new jobs
     *
     * Generated from protobuf field <code>bool should_drain = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setShouldDrain($var)
    {
        GPBUtil::checkBool($var);
        $this->should_drain = $var;

        return $this;
    }

}

