<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Job message
 *
 * Generated from protobuf message <code>spooled.v1.Job</code>
 */
class Job extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string organization_id = 2;</code>
     */
    protected $organization_id = '';
    /**
     * Generated from protobuf field <code>string queue_name = 3;</code>
     */
    protected $queue_name = '';
    /**
     * Generated from protobuf field <code>.spooled.v1.JobStatus status = 4;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 5;</code>
     */
    protected $payload = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct result = 6;</code>
     */
    protected $result = null;
    /**
     * Generated from protobuf field <code>int32 retry_count = 7;</code>
     */
    protected $retry_count = 0;
    /**
     * Generated from protobuf field <code>int32 max_retries = 8;</code>
     */
    protected $max_retries = 0;
    /**
     * Generated from protobuf field <code>string last_error = 9;</code>
     */
    protected $last_error = '';
    /**
     * Generated from protobuf field <code>int32 priority = 10;</code>
     */
    protected $priority = 0;
    /**
     * Generated from protobuf field <code>int32 timeout_seconds = 11;</code>
     */
    protected $timeout_seconds = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_at = 13;</code>
     */
    protected $scheduled_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 14;</code>
     */
    protected $started_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp completed_at = 15;</code>
     */
    protected $completed_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lease_expires_at = 16;</code>
     */
    protected $lease_expires_at = null;
    /**
     * Generated from protobuf field <code>string assigned_worker_id = 17;</code>
     */
    protected $assigned_worker_id = '';
    /**
     * Generated from protobuf field <code>string idempotency_key = 18;</code>
     */
    protected $idempotency_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $organization_id
     *     @type string $queue_name
     *     @type int $status
     *     @type \Google\Protobuf\Struct $payload
     *     @type \Google\Protobuf\Struct $result
     *     @type int $retry_count
     *     @type int $max_retries
     *     @type string $last_error
     *     @type int $priority
     *     @type int $timeout_seconds
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $scheduled_at
     *     @type \Google\Protobuf\Timestamp $started_at
     *     @type \Google\Protobuf\Timestamp $completed_at
     *     @type \Google\Protobuf\Timestamp $lease_expires_at
     *     @type string $assigned_worker_id
     *     @type string $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string organization_id = 2;</code>
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Generated from protobuf field <code>string organization_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->organization_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 3;</code>
     * @return string
     */
    public function getQueueName()
    {
        return $this->queue_name;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQueueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.JobStatus status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.JobStatus status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Spooled\V1\JobStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 5;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getPayload()
    {
        return $this->payload;
    }

    public function hasPayload()
    {
        return isset($this->payload);
    }

    public function clearPayload()
    {
        unset($this->payload);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 5;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct result = 6;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct result = 6;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 retry_count = 7;</code>
     * @return int
     */
    public function getRetryCount()
    {
        return $this->retry_count;
    }

    /**
     * Generated from protobuf field <code>int32 retry_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setRetryCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->retry_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_retries = 8;</code>
     * @return int
     */
    public function getMaxRetries()
    {
        return $this->max_retries;
    }

    /**
     * Generated from protobuf field <code>int32 max_retries = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRetries($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_retries = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_error = 9;</code>
     * @return string
     */
    public function getLastError()
    {
        return $this->last_error;
    }

    /**
     * Generated from protobuf field <code>string last_error = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLastError($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 priority = 10;</code>
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Generated from protobuf field <code>int32 priority = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkInt32($var);
        $this->priority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 timeout_seconds = 11;</code>
     * @return int
     */
    public function getTimeoutSeconds()
    {
        return $this->timeout_seconds;
    }

    /**
     * Generated from protobuf field <code>int32 timeout_seconds = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeoutSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeout_seconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 12;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_at = 13;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getScheduledAt()
    {
        return $this->scheduled_at;
    }

    public function hasScheduledAt()
    {
        return isset($this->scheduled_at);
    }

    public function clearScheduledAt()
    {
        unset($this->scheduled_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_at = 13;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setScheduledAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->scheduled_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 14;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    public function hasStartedAt()
    {
        return isset($this->started_at);
    }

    public function clearStartedAt()
    {
        unset($this->started_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 14;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp completed_at = 15;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCompletedAt()
    {
        return $this->completed_at;
    }

    public function hasCompletedAt()
    {
        return isset($this->completed_at);
    }

    public function clearCompletedAt()
    {
        unset($this->completed_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp completed_at = 15;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCompletedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->completed_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lease_expires_at = 16;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLeaseExpiresAt()
    {
        return $this->lease_expires_at;
    }

    public function hasLeaseExpiresAt()
    {
        return isset($this->lease_expires_at);
    }

    public function clearLeaseExpiresAt()
    {
        unset($this->lease_expires_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lease_expires_at = 16;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLeaseExpiresAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->lease_expires_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assigned_worker_id = 17;</code>
     * @return string
     */
    public function getAssignedWorkerId()
    {
        return $this->assigned_worker_id;
    }

    /**
     * Generated from protobuf field <code>string assigned_worker_id = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setAssignedWorkerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->assigned_worker_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 18;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->idempotency_key = $var;

        return $this;
    }

}
