<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use UnexpectedValueException;

/**
 * Job status enumeration
 *
 * Protobuf type <code>spooled.v1.JobStatus</code>
 */
class JobStatus
{
    /**
     * Generated from protobuf enum <code>JOB_STATUS_UNSPECIFIED = 0;</code>
     */
    const JOB_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>JOB_STATUS_PENDING = 1;</code>
     */
    const JOB_STATUS_PENDING = 1;
    /**
     * Generated from protobuf enum <code>JOB_STATUS_SCHEDULED = 2;</code>
     */
    const JOB_STATUS_SCHEDULED = 2;
    /**
     * Generated from protobuf enum <code>JOB_STATUS_PROCESSING = 3;</code>
     */
    const JOB_STATUS_PROCESSING = 3;
    /**
     * Generated from protobuf enum <code>JOB_STATUS_COMPLETED = 4;</code>
     */
    const JOB_STATUS_COMPLETED = 4;
    /**
     * Generated from protobuf enum <code>JOB_STATUS_FAILED = 5;</code>
     */
    const JOB_STATUS_FAILED = 5;
    /**
     * Generated from protobuf enum <code>JOB_STATUS_DEADLETTER = 6;</code>
     */
    const JOB_STATUS_DEADLETTER = 6;
    /**
     * Generated from protobuf enum <code>JOB_STATUS_CANCELLED = 7;</code>
     */
    const JOB_STATUS_CANCELLED = 7;

    private static $valueToName = [
        self::JOB_STATUS_UNSPECIFIED => 'JOB_STATUS_UNSPECIFIED',
        self::JOB_STATUS_PENDING => 'JOB_STATUS_PENDING',
        self::JOB_STATUS_SCHEDULED => 'JOB_STATUS_SCHEDULED',
        self::JOB_STATUS_PROCESSING => 'JOB_STATUS_PROCESSING',
        self::JOB_STATUS_COMPLETED => 'JOB_STATUS_COMPLETED',
        self::JOB_STATUS_FAILED => 'JOB_STATUS_FAILED',
        self::JOB_STATUS_DEADLETTER => 'JOB_STATUS_DEADLETTER',
        self::JOB_STATUS_CANCELLED => 'JOB_STATUS_CANCELLED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

