<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Process Request (for bidirectional streaming)
 *
 * Generated from protobuf message <code>spooled.v1.ProcessRequest</code>
 */
class ProcessRequest extends \Google\Protobuf\Internal\Message
{
    protected $request;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spooled\V1\DequeueRequest $dequeue
     *     @type \Spooled\V1\CompleteRequest $complete
     *     @type \Spooled\V1\FailRequest $fail
     *     @type \Spooled\V1\RenewLeaseRequest $renew_lease
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.DequeueRequest dequeue = 1;</code>
     * @return \Spooled\V1\DequeueRequest|null
     */
    public function getDequeue()
    {
        return $this->readOneof(1);
    }

    public function hasDequeue()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.DequeueRequest dequeue = 1;</code>
     * @param \Spooled\V1\DequeueRequest $var
     * @return $this
     */
    public function setDequeue($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\DequeueRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.CompleteRequest complete = 2;</code>
     * @return \Spooled\V1\CompleteRequest|null
     */
    public function getComplete()
    {
        return $this->readOneof(2);
    }

    public function hasComplete()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.CompleteRequest complete = 2;</code>
     * @param \Spooled\V1\CompleteRequest $var
     * @return $this
     */
    public function setComplete($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\CompleteRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.FailRequest fail = 3;</code>
     * @return \Spooled\V1\FailRequest|null
     */
    public function getFail()
    {
        return $this->readOneof(3);
    }

    public function hasFail()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.FailRequest fail = 3;</code>
     * @param \Spooled\V1\FailRequest $var
     * @return $this
     */
    public function setFail($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\FailRequest::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.RenewLeaseRequest renew_lease = 4;</code>
     * @return \Spooled\V1\RenewLeaseRequest|null
     */
    public function getRenewLease()
    {
        return $this->readOneof(4);
    }

    public function hasRenewLease()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.RenewLeaseRequest renew_lease = 4;</code>
     * @param \Spooled\V1\RenewLeaseRequest $var
     * @return $this
     */
    public function setRenewLease($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\RenewLeaseRequest::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

