<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Process Response (for bidirectional streaming)
 *
 * Generated from protobuf message <code>spooled.v1.ProcessResponse</code>
 */
class ProcessResponse extends \Google\Protobuf\Internal\Message
{
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spooled\V1\Job $job
     *     @type \Spooled\V1\CompleteResponse $complete
     *     @type \Spooled\V1\FailResponse $fail
     *     @type \Spooled\V1\RenewLeaseResponse $renew_lease
     *     @type \Spooled\V1\ErrorResponse $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.Job job = 1;</code>
     * @return \Spooled\V1\Job|null
     */
    public function getJob()
    {
        return $this->readOneof(1);
    }

    public function hasJob()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.Job job = 1;</code>
     * @param \Spooled\V1\Job $var
     * @return $this
     */
    public function setJob($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\Job::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.CompleteResponse complete = 2;</code>
     * @return \Spooled\V1\CompleteResponse|null
     */
    public function getComplete()
    {
        return $this->readOneof(2);
    }

    public function hasComplete()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.CompleteResponse complete = 2;</code>
     * @param \Spooled\V1\CompleteResponse $var
     * @return $this
     */
    public function setComplete($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\CompleteResponse::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.FailResponse fail = 3;</code>
     * @return \Spooled\V1\FailResponse|null
     */
    public function getFail()
    {
        return $this->readOneof(3);
    }

    public function hasFail()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.FailResponse fail = 3;</code>
     * @param \Spooled\V1\FailResponse $var
     * @return $this
     */
    public function setFail($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\FailResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.RenewLeaseResponse renew_lease = 4;</code>
     * @return \Spooled\V1\RenewLeaseResponse|null
     */
    public function getRenewLease()
    {
        return $this->readOneof(4);
    }

    public function hasRenewLease()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.RenewLeaseResponse renew_lease = 4;</code>
     * @param \Spooled\V1\RenewLeaseResponse $var
     * @return $this
     */
    public function setRenewLease($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\RenewLeaseResponse::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.ErrorResponse error = 5;</code>
     * @return \Spooled\V1\ErrorResponse|null
     */
    public function getError()
    {
        return $this->readOneof(5);
    }

    public function hasError()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.spooled.v1.ErrorResponse error = 5;</code>
     * @param \Spooled\V1\ErrorResponse $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Spooled\V1\ErrorResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

