<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Worker Registration
 *
 * Generated from protobuf message <code>spooled.v1.RegisterWorkerRequest</code>
 */
class RegisterWorkerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     */
    protected $queue_name = '';
    /**
     * Generated from protobuf field <code>string hostname = 2;</code>
     */
    protected $hostname = '';
    /**
     * Generated from protobuf field <code>string worker_type = 3;</code>
     */
    protected $worker_type = '';
    /**
     * Generated from protobuf field <code>int32 max_concurrency = 4;</code>
     */
    protected $max_concurrency = 0;
    /**
     * Generated from protobuf field <code>string version = 5;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>map<string, string> metadata = 6;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $queue_name
     *     @type string $hostname
     *     @type string $worker_type
     *     @type int $max_concurrency
     *     @type string $version
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @return string
     */
    public function getQueueName()
    {
        return $this->queue_name;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQueueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hostname = 2;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string worker_type = 3;</code>
     * @return string
     */
    public function getWorkerType()
    {
        return $this->worker_type;
    }

    /**
     * Generated from protobuf field <code>string worker_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkerType($var)
    {
        GPBUtil::checkString($var, True);
        $this->worker_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_concurrency = 4;</code>
     * @return int
     */
    public function getMaxConcurrency()
    {
        return $this->max_concurrency;
    }

    /**
     * Generated from protobuf field <code>int32 max_concurrency = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxConcurrency($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_concurrency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 5;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

}

