<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Worker Registration Response
 *
 * Generated from protobuf message <code>spooled.v1.RegisterWorkerResponse</code>
 */
class RegisterWorkerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string worker_id = 1;</code>
     */
    protected $worker_id = '';
    /**
     * Generated from protobuf field <code>int32 lease_duration_secs = 2;</code>
     */
    protected $lease_duration_secs = 0;
    /**
     * Generated from protobuf field <code>int32 heartbeat_interval_secs = 3;</code>
     */
    protected $heartbeat_interval_secs = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $worker_id
     *     @type int $lease_duration_secs
     *     @type int $heartbeat_interval_secs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string worker_id = 1;</code>
     * @return string
     */
    public function getWorkerId()
    {
        return $this->worker_id;
    }

    /**
     * Generated from protobuf field <code>string worker_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->worker_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 lease_duration_secs = 2;</code>
     * @return int
     */
    public function getLeaseDurationSecs()
    {
        return $this->lease_duration_secs;
    }

    /**
     * Generated from protobuf field <code>int32 lease_duration_secs = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLeaseDurationSecs($var)
    {
        GPBUtil::checkInt32($var);
        $this->lease_duration_secs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 heartbeat_interval_secs = 3;</code>
     * @return int
     */
    public function getHeartbeatIntervalSecs()
    {
        return $this->heartbeat_interval_secs;
    }

    /**
     * Generated from protobuf field <code>int32 heartbeat_interval_secs = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHeartbeatIntervalSecs($var)
    {
        GPBUtil::checkInt32($var);
        $this->heartbeat_interval_secs = $var;

        return $this;
    }

}
