<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Renew Lease Request
 *
 * Generated from protobuf message <code>spooled.v1.RenewLeaseRequest</code>
 */
class RenewLeaseRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     */
    protected $job_id = '';
    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     */
    protected $worker_id = '';
    /**
     * Generated from protobuf field <code>int32 extension_secs = 3;</code>
     */
    protected $extension_secs = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $job_id
     *     @type string $worker_id
     *     @type int $extension_secs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->job_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     * @return string
     */
    public function getWorkerId()
    {
        return $this->worker_id;
    }

    /**
     * Generated from protobuf field <code>string worker_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->worker_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 extension_secs = 3;</code>
     * @return int
     */
    public function getExtensionSecs()
    {
        return $this->extension_secs;
    }

    /**
     * Generated from protobuf field <code>int32 extension_secs = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setExtensionSecs($var)
    {
        GPBUtil::checkInt32($var);
        $this->extension_secs = $var;

        return $this;
    }

}
