<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spooled.proto

namespace Spooled\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Renew Lease Response
 *
 * Generated from protobuf message <code>spooled.v1.RenewLeaseResponse</code>
 */
class RenewLeaseResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp new_expires_at = 2;</code>
     */
    protected $new_expires_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type \Google\Protobuf\Timestamp $new_expires_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spooled::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp new_expires_at = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getNewExpiresAt()
    {
        return $this->new_expires_at;
    }

    public function hasNewExpiresAt()
    {
        return isset($this->new_expires_at);
    }

    public function clearNewExpiresAt()
    {
        unset($this->new_expires_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp new_expires_at = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setNewExpiresAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->new_expires_at = $var;

        return $this;
    }

}

